package com.example.dynamodb.demo.config.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.stereotype.Component;

/**
 * Copyright (c) 2021 All Rights Reserved
 * Created by Kalana Weerarathne on 11/03/2021 7:45 AM.
 */
@DynamoDBTable(tableName = "books")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Component
public class Book {
    //annotation for marking the property as the hashkey
    @DynamoDBHashKey(attributeName = "id")
    //annotation for making the hashkey property to autogenerate
    //the key. supports string datatype only
    @DynamoDBAutoGeneratedKey
    String id;
    //describes the field name as it will be represented in dynamodb table
    //offers the name to be different than the field name of the class
    @DynamoDBAttribute
    String title;

    @DynamoDBAttribute
    String author;

    @DynamoDBAttribute
    String genre;

    @DynamoDBAttribute
    String publisher;

    @DynamoDBAttribute
    int quantity;
}
